Tue, 17 Jan 2023 08:04:54 GMT
catchAll error
Stack: Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\auth-logic.ts:20:15)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\auth-logic.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
----------------------------------------------------------------------------------------------------
Tue, 17 Jan 2023 08:04:56 GMT
catchAll error
Stack: Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\auth-logic.ts:20:15)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\auth-logic.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
----------------------------------------------------------------------------------------------------
Tue, 17 Jan 2023 08:05:15 GMT
catchAll error
Stack: Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\auth-logic.ts:20:15)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\auth-logic.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
----------------------------------------------------------------------------------------------------
Thu, 19 Jan 2023 10:47:20 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DATE_FORMAT(checkIn, '%d/%m/%Y'), DATE_FORMAT(checkOut, '%d/%m/%Y') FROM vaca...' at line 1
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:15:33)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getAllVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:21:12)
----------------------------------------------------------------------------------------------------
Thu, 19 Jan 2023 10:47:23 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DATE_FORMAT(checkIn, '%d/%m/%Y'), DATE_FORMAT(checkOut, '%d/%m/%Y') FROM vaca...' at line 1
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:15:33)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getAllVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:21:12)
----------------------------------------------------------------------------------------------------
Thu, 19 Jan 2023 11:00:40 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE DATE_FORMAT(checkIn, '%d/%m/%Y'), DATE_FORMAT(checkOut, '%d/%m/%Y') FRO...' at line 1
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:15:33)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getAllVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:21:12)
----------------------------------------------------------------------------------------------------
Thu, 19 Jan 2023 11:01:00 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM vacations WHERE DATE_FORMAT(checkIn, '%d/%m/%Y'), DATE_FORMAT(checkOut, ...' at line 1
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:15:33)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getAllVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:21:12)
----------------------------------------------------------------------------------------------------
Thu, 19 Jan 2023 15:53:33 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS isFollowing
    FROM vacations AS V LEFT JOIN followers AS F
    ON V.vaca...' at line 3
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:46:33)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getVacationsForUser (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:31:12)
----------------------------------------------------------------------------------------------------
Sat, 21 Jan 2023 17:13:59 GMT
catchAll error
Stack: Error: ER_BAD_NULL_ERROR: Column 'userId' cannot be null
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:18:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Sat, 21 Jan 2023 17:16:45 GMT
catchAll error
Stack: Error: ER_BAD_NULL_ERROR: Column 'userId' cannot be null
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:18:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Sun, 22 Jan 2023 06:35:13 GMT
catchAll error
Stack: Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\auth-logic.ts:49:29)
    at Generator.next (<anonymous>)
----------------------------------------------------------------------------------------------------
Sun, 22 Jan 2023 06:35:30 GMT
catchAll error
Stack: Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\auth-logic.ts:49:29)
    at Generator.next (<anonymous>)
----------------------------------------------------------------------------------------------------
Sun, 22 Jan 2023 10:04:09 GMT
catchAll error
Stack: Error: ER_BAD_NULL_ERROR: Column 'followersAmount' cannot be null
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:64:38)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
----------------------------------------------------------------------------------------------------
Sun, 22 Jan 2023 10:21:29 GMT
catchAll error
Stack: Error: ER_BAD_NULL_ERROR: Column 'followersAmount' cannot be null
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:64:38)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:05:37 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:09:39 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:10:53 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:12:49 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:24:38 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:24:40 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:36:27 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:37:05 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:37:06 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:41:12 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:48:11 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:55:07 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:55:31 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:55:48 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:56:13 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:56:59 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:58:00 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:58:21 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 10:58:34 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 11:15:40 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`))
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:16:15)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:4:12)
    at Object.addFollower (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\followers-logic.ts:19:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 11:47:18 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ORDER BY isFollowing ASC' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:38:33)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getVacationsForUser (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:31:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 11:47:30 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ORDER BY isFollowing ASC' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:38:33)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getVacationsForUser (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:31:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 11:47:44 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ORDER BY isFollowing ASC' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:38:33)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getVacationsForUser (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:31:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 11:49:42 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ORDER BY isFollowing ASC' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:38:33)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getVacationsForUser (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:31:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 12:08:28 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'V.isFollowing' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:161:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 12:09:16 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'V.isFollowing' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:161:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 12:10:28 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'V.isFollowing' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:161:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 12:11:27 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'V.isFollowing' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:161:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 12:11:33 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'V.isFollowing' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:161:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 12:38:42 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?) AS isFollowing,
        FROM vacations AS V LEFT JOIN followers AS F
     ...' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:163:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 12:41:06 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?) AS isFollowing,
        FROM vacations AS V LEFT JOIN followers AS F
     ...' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:163:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 12:46:21 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?) AS isFollowing,
        FROM vacations AS V LEFT JOIN followers AS F
     ...' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:163:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 12:48:23 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?) AS isFollowing,
        FROM vacations AS V LEFT JOIN followers AS F
     ...' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:163:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 12:49:03 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?) AS isFollowing
        FROM vacations AS V LEFT JOIN followers AS F
      ...' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:163:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 12:49:05 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?) AS isFollowing
        FROM vacations AS V LEFT JOIN followers AS F
      ...' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:163:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 12:51:29 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'isFollowing' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:163:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 12:54:14 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'isFollowing' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:163:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 13:25:10 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'EXISTS(SELECT * FROM followers WHERE vacationId = F.vacationId AND userId = 2...' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:164:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 13:25:11 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'EXISTS(SELECT * FROM followers WHERE vacationId = F.vacationId AND userId = 2...' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:164:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 13:25:33 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'EXISTS(SELECT * FROM followers WHERE vacationId = F.vacationId AND userId = 2...' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:164:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 13:25:34 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'EXISTS(SELECT * FROM followers WHERE vacationId = F.vacationId AND userId = 2...' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:164:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Tue, 24 Jan 2023 13:26:39 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'EXISTS(SELECT * FROM followers WHERE vacationId = F.vacationId AND userId = 2...' at line 9
    at Query.Sequence._packetToError (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:164:31)
    at Generator.next (<anonymous>)
    at C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getFollowedVacations (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:134:12)
----------------------------------------------------------------------------------------------------
Sat, 28 Jan 2023 18:28:36 GMT
catchAll error
Stack: Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
    --------------------
    at Protocol._enqueue (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:22:33)
    at Generator.next (<anonymous>)
----------------------------------------------------------------------------------------------------
Sat, 28 Jan 2023 18:32:21 GMT
catchAll error
Stack: Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
    --------------------
    at Protocol._enqueue (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\vacations-logic.ts:22:33)
    at Generator.next (<anonymous>)
----------------------------------------------------------------------------------------------------
Sat, 28 Jan 2023 18:32:48 GMT
catchAll error
Stack: Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
    --------------------
    at Protocol._enqueue (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\auth-logic.ts:49:29)
    at Generator.next (<anonymous>)
----------------------------------------------------------------------------------------------------
Sat, 28 Jan 2023 18:33:24 GMT
catchAll error
Stack: Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
    --------------------
    at Protocol._enqueue (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\auth-logic.ts:49:29)
    at Generator.next (<anonymous>)
----------------------------------------------------------------------------------------------------
Sun, 29 Jan 2023 16:17:59 GMT
catchAll error
Stack: Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
    --------------------
    at Protocol._enqueue (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\97254\Desktop\Third project\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:13:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\97254\Desktop\Third project\Backend\src\2-utils\dal.ts:12:12)
    at Object.<anonymous> (C:\Users\97254\Desktop\Third project\Backend\src\5-logic\auth-logic.ts:17:29)
    at Generator.next (<anonymous>)
----------------------------------------------------------------------------------------------------
